name: 'GitHub Actions SCUT SIGN IN'

on:
  watch:
    types: started  # 当有人开始关注这个仓库时触发
  push:  # 当有推送到这个仓库时触发
  schedule:
    - cron: '30 22 * * *'  # 每天 UTC 时间 9:00 触发

jobs:
  bot:
    runs-on: ubuntu-latest  # 指定运行环境为最新的 Ubuntu
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1  # 检出仓库代码
      
      - name: 'Set up Python'
        uses: actions/setup-python@v1  # 设置 Python 环境
        with:
          python-version: '3.8'  # 指定 Python 版本为 3.7

      - name: 'Install requirements'
        run: |
          python -m pip install --upgrade pip  # 升级 pip
          pip install -r requirements.txt  # 从 requirements.txt 安装所需的 Python 包

      - name: 'flowRate_warnRemotegithub'
        env:
          CC_USERNAME: ${{ secrets.CC_USERNAME }}  # 使用密钥 SITYUN_USER 作为环境变量
          CC_PASSWORD: ${{ secrets.CC_PASSWORD }}  # 使用密钥 SITYUN_PASSWORD 作为环境变量
          PUSHPLUS: ${{ secrets.PUSHPLUS}}
        run: python flowRate_warnRemotegithub.py  # 运行 flowRate_warnRemotegithub.py 脚本
